api_platform:
    title: 'Your API Title'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    enable_swagger_ui: true
    enable_docs: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    collection:
        pagination:
            enabled: true
            items_per_page_parameter_name: 'itemsPerPage'
            page_parameter_name: 'page'
