gesdinet_jwt_refresh_token:
    ttl: 2592000
    ttl_update: true
    user_provider: users_in_memory
    user_identity_field: email
    manager_type: orm
    refresh_token_entity: App\Entity\RefreshToken
