security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api_login:
            pattern: ^/api/login$
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            stateless: true
            provider: users_in_memory
            jwt: ~

            logout:
                path: app_logout
                invalidate_session: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # Autoriser l'accès à /api pour tout le monde
        - { path: ^/api$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Autoriser l'accès sans authentification uniquement à la route /api/login
        - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Pour toutes les autres routes API, l'authentification est requise
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
