controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

gesdinet_jwt_refresh_token:
    path: /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]

discussion_filter:
    resource: '../src/Controller/DiscussionFilterController.php'
    type: attribute

upload_image:
    path: /api/articles/upload-image
    controller: App\Controller\UploadImageController
    methods: POST

