name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-pipeline:
    name: Backend Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Clear Cache
        run: php bin/console cache:clear --env=prod

      - name: Verify Symfony is Installed
        run: php bin/console --version
