name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: paceeDB
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          cp .env.test .env

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Create database and schema
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:update --force --env=test

      - name: Run PHPUnit
        run: |
          php bin/phpunit --colors=always
